### ISSUE TITLE
Skeletons behaviour

### ISSUE THREAD

**Issue by SquareBall789** [MidnightsFX/Valheim_Fortress#2] opened 2023-11-04 18:23 UTC
skeletons run away from portal, attack other normally spawned mobs and drop bone fragments. This could be a bug that only happens on multiplayer however.

**Comment by MidnightsFX** [comment] 2023-11-04 19:02
What version is this occuring on for you?

**Comment by SquareBall789** [comment] 2023-11-04 20:47
> What version is this occuring on for you?

Mod Version is 0.6.0
Game Ver is 0.217.25

**Comment by MidnightsFX** [comment] 2023-11-04 21:35
Interesting! What level of the shrine are you spawning?

**Comment by SquareBall789** [comment] 2023-11-04 21:37
Any of the black forest ones, we haven't got any higher yet

**Comment by MidnightsFX** [comment] 2023-11-07 00:48
Have you rebuild the shrine since updating to the newer version?

Also if you are playing on multiplayer is the server updated?

**Comment by MidnightsFX** [comment] 2023-11-09 03:20
If this is still occurring for you can you enable debug mode from the config and send me the server bepinex logs and the players logs?

I believe this should have been fixed in a previous update though.

**Comment by MidnightsFX** [comment] 2023-11-13 03:55
Closing this as I can't reproduce it on newer versions and I don't have any additional leads on if it is still an issue.

**Closed as completed by MidnightsFX** 2023-11-13 03:55 UTC
Labels: bug, question
